C++ = g++

DEBUG = 1
STATIC = 0

CCFLAGS = -I./ -I../udt -I../gmp -I../routing -I../client -I../server
LDFLAGS = -lstdc++ -lpthread -L. -L../lib #../libduma.a -u malloc

ifeq ($(DEBUG), 1)
   CCFLAGS += -Wall -g
endif

ifeq ($(STATIC), 1)
   LDFLAGS += -static
endif
