C++ = g++

DEBUG = 0
STATIC = 0
EFENCE = 0

CCFLAGS = -I./ -I../util -I../gmp -I../routing -I../udt -I../sql -I../metadata
LDFLAGS = -lstdc++ -lpthread -L. -L../lib -lutil

ifeq ($(DEBUG), 1)
   CCFLAGS += -Wall -g
endif

ifeq ($(STATIC), 1)
   LDFLAGS += -static
endif

ifeq ($(EFENCE), 1)
   LDFLAGS += ../libefence.a -u malloc
endif
