C++ = g++

DEBUG = 1
STATIC = 0

CCFLAGS = -I. -I../include -I../udt
LDFLAGS = -lstdc++ -lpthread -lssl -lcrypto -L.

WARNING = -Wall -Wextra -Werror 
#-pedantic -Woverloaded-virtual -Wnon-virtual-dtor -Wcomment -Wstrict-null-sentinel -Wconversion -Wcast-align -Wcast-qual -Winit-self -Weffc++

ifeq ($(DEBUG), 1)
   CCFLAGS += -g -DDEBUG $(WARNING)
else
   CCFLAGS += -O3
endif
