C++ = g++

DEBUG = 1
STATIC = 0

CCFLAGS = -I./ -I../udt -I../gmp -I../common -I../security 
LDFLAGS = -lstdc++ -lpthread -lssl -L. -L../lib -ludt -lrpc -lcommon -lsecurity

ifeq ($(DEBUG), 1)
   CCFLAGS += -Wall -g
endif

ifeq ($(STATIC), 1)
   LDFLAGS += -static
endif
